import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { formatReportValue } from "./reportFormat";
import "./ReportPrint.css";

export function ReportTable({ section }) {
  return <table className="report-data-table">
    <colgroup>{section.columns.map((column) => <col key={column.key} style={{ width: ({ name: "26%", product: "26%", product_id: "9%", transaction_id: "12%", delivery_id: "9%", items: "32%", products: "32%", quantity: "10%", vendor: "17%", staff: "17%" })[column.key] }} />)}</colgroup>
    <thead><tr>{section.columns.map((column) => <th key={column.key} scope="col" className={column.type === "money" || column.type === "number" ? "is-numeric" : ""}>{column.label}</th>)}</tr></thead>
    <tbody>{section.rows.length ? section.rows.map((row, index) => <tr key={index}>
      {section.columns.map((column) => <td key={column.key} data-label={column.label} className={column.type === "money" || column.type === "number" ? "is-numeric" : ""}>{formatReportValue(row[column.key], column.type)}</td>)}
    </tr>) : <tr><td colSpan={section.columns.length}>No records for the selected dates.</td></tr>}</tbody>
  </table>;
}

export function ReportDocument({ report }) {
  const period = report.period.start_date === report.period.end_date
    ? formatReportValue(report.period.start_date, "date")
    : `${formatReportValue(report.period.start_date, "date")} – ${formatReportValue(report.period.end_date, "date")}`;
  const generated = new Intl.DateTimeFormat("en-PH", { timeZone: report.time_zone, dateStyle: "medium", timeStyle: "short" }).format(new Date(report.generated_at));
  const generatedDate = new Intl.DateTimeFormat("en-PH", { timeZone: report.time_zone, dateStyle: "medium" }).format(new Date(report.generated_at));
  return <article className="report-paper">
    <header className="report-paper-header">
      <div className="report-brand-mark" aria-hidden="true">NCSA</div>
      <div><p className="report-organization">{report.organization}</p><p className="report-system-label">Operations and sales reporting</p></div>
    </header>
    <h1>{report.title}</h1>
    <dl className="report-paper-meta">
      <div><dt>Report reference</dt><dd>{report.report_id}</dd></div>
      <div><dt>Reporting period</dt><dd>{report.period.scope === "all-time" ? "All time: " : ""}{period}</dd></div>
      <div><dt>Prepared by</dt><dd>{report.prepared_by}</dd></div>
      <div><dt>Generated</dt><dd>{generated} ({report.time_zone})</dd></div>
    </dl>
    <section className="report-paper-summary">
      <h2>Summary</h2>
      <table className="report-summary-table"><thead><tr><th scope="col">Description</th><th scope="col">Total</th></tr></thead><tbody>{report.summary.map((item) => <tr key={item.label} className={item.label === "Net sales" ? "is-total" : ""}><td>{item.label}</td><td>{formatReportValue(item.value, item.type)}</td></tr>)}</tbody></table>
    </section>
    {report.sections.map((section) => <section className="report-paper-section" key={section.title}>
      <h2>{section.title}</h2><ReportTable section={section} />
    </section>)}
    <section className="report-paper-notes"><h2>Report notes</h2><p>{report.note}</p></section>
    <div className="report-signatures">
      <div><span>Prepared by</span><strong>{report.prepared_by}</strong><small>Date: {generatedDate}</small></div>
      <div><span>Reviewed / noted by</span><strong>&nbsp;</strong><small>Name, signature, and date</small></div>
    </div>
    <footer className="report-paper-footer">Generated by New Clarin Sports Arena POS. Amounts are in Philippine pesos (PHP).</footer>
  </article>;
}

export default function ReportPrintPreview({ report, onBack }) {
  const [error, setError] = useState("");
  useEffect(() => {
    const previousTitle = document.title;
    document.title = `${report.title} - ${report.period.start_date}`;
    document.body.classList.add("printing-report");
    return () => { document.body.classList.remove("printing-report"); document.title = previousTitle; };
  }, [report]);
  function printReport() {
    try {
      if (typeof window.print !== "function") throw new Error();
      setError("");
      // Invoked directly by a user gesture; no pop-up, async fetch or iframe.
      window.print();
    } catch {
      setError("This browser could not open printing. Open this page in Chrome, Edge, or Safari and try again.");
    }
  }
  return <div className="report-print-preview">
    <div className="report-print-toolbar">
      <button type="button" className="report-back-button" onClick={onBack}>Back to reports</button>
      <div><strong>Print preview</strong><span>Choose your printer or Save as PDF in the system print dialog.</span></div>
      <button type="button" className="reports-export-button" onClick={printReport}>Print / Save PDF</button>
    </div>
    <p className="report-print-help">Use A4 or Letter paper, portrait layout. On mobile, open in a full browser with a configured print service. Browser print settings control printer, copies, and paper size.</p>
    {error && <p role="alert" className="error-message">{error}</p>}
    <p className="report-preview-scroll-hint">Swipe horizontally on the paper preview to see all columns. The printed report uses the full paper width.</p>
    <div className="report-preview-paper" tabIndex={0} role="region" aria-label="Printable report preview"><ReportDocument report={report} /></div>
    {createPortal(<div className="report-print-root"><ReportDocument report={report} /></div>, document.body)}
  </div>;
}
